include: package:very_good_analysis/analysis_options.yaml
formatter: 
  trailing_commas: preserve 
linter:
  rules:
    public_member_api_docs: false # todo: remove when all expression will be implemented
